version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    
    volumes:
      - ./src:/app/src
      - ./templates:/app/templates
      - ./static:/app/static
    environment:
      - FLASK_DEBUG=1